-- Healthcare Data Analysis Project SQL Queries
CREATE DATABASE IF NOT EXISTS healthcare_db;
USE healthcare_db;

-- 1. Total Patients & Overall Billing Amount
SELECT 
    COUNT(*) AS Total_Patients, 
    ROUND(SUM(Billing_Amount), 2) AS Total_Billing 
FROM healthcare_data;

-- 2. Medical Condition Breakdown & Average Billing
SELECT 
    Medical_Condition, 
    COUNT(*) AS Patient_Count, 
    ROUND(AVG(Billing_Amount), 2) AS Avg_Billing 
FROM healthcare_data 
GROUP BY Medical_Condition;

-- 3. Top 5 Hospitals by Patient Count
SELECT 
    Hospital, 
    COUNT(*) AS Patient_Count 
FROM healthcare_data 
GROUP BY Hospital 
ORDER BY Patient_Count DESC 
LIMIT 5;

-- 4. Admission Type Breakdown
SELECT 
    Admission_Type, 
    COUNT(*) AS Patient_Count 
FROM healthcare_data 
GROUP BY Admission_Type;

-- 5. Revenue Generated by Insurance Providers
SELECT 
    Insurance_Provider, 
    ROUND(SUM(Billing_Amount), 2) AS Total_Claimed 
FROM healthcare_data 
GROUP BY Insurance_Provider 
ORDER BY Total_Claimed DESC;
